### ISSUE TITLE
Базовый UI

### ISSUE THREAD

**Issue by dlykoits** [anex13/Dipapp#3]
1) Создай основное Activity.
2) Добавь боковое меню(NavigationDrawer см; http://android-developers.blogspot.com.by/2015/05/android-design-support-library.html)
3) Добавь пункты в боковое меню и соответсвенно пустые фрагменты.
4) Прикрути переходы между фрагментами по нажатию на боковое меню

**Comment by anex13** [comment]
почитать про фрагменты 
и про интенты и адаптеры листы

**Comment by anex13** [comment]
delay на недельку т.к. госы с пн начинаются но буду читать и попробую запилить то что ты сказал
